/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package example

object App {
  def main(args: Array[String]): Unit = {
    println(greeting("v2-beta"))
  }

  def greeting(who: String): String = s"Hello, ${who}!"
}
