/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package example

object App {
  def main(args: Array[String]): Unit = {
    println(greeting("v2"))
  }

  def greeting(version: String): String = s"Welcome to version: ${version}!"
}
